management:
  endpoints:
    web:
      exposure:
        include: health

server:
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

logging:
  level:
    com.example.todo: WARN
    org.springframework.security: WARN
