management:
  endpoints:
    web:
      exposure:
        include: health

server:
  error:
    include-message: never
    include-stacktrace: never

logging:
  level:
    com.example.todo: INFO
    org.springframework.security: INFO
